### ISSUE TITLE
VI clone "memory leak" if ModbusTCP open/closed in loop

### ISSUE THREAD

**Issue by drjdpowell** [rfporter/Modbus-Master#4]
The following code creates a new Clone on each call.   These clones don't seem to be reused, and they build up in memory.  I noticed this with code that connects in a loop every few seconds.
![2021-11-24 13_58_22-MB Master lvlib_MB_Master_TCP lvclass_Open TCP Session vi Block Diagram on Endur](https://user-images.githubusercontent.com/6072800/143254253-3cde5ccc-8108-455e-b2da-10cab4b07e1f.png)

A secondary problem with creating clones like this is that it is blocked by Root Loop.

I hacked a fix to use a Clone Pool (option 0x40) here.  Did on First Call, but a more robust way is to do it like in the Actor Framework.

![2021-11-24 14_07_20-MB Master lvlib_MB_Master_TCP lvclass_Open TCP Session vi Block Diagram on Endur](https://user-images.githubusercontent.com/6072800/143254509-437af161-c344-4695-a95c-d2a72476bc84.png)

**Comment by rfporter** [comment]
Ah. I hadn't thought about the root loop.

In your code, do you close the modbus session before opening an new session?
For example:
![Capture](https://user-images.githubusercontent.com/6878763/143512855-b42bceac-aae7-45de-b693-a76eb4ceee7e.PNG)

**Comment by drjdpowell** [comment]
Yes, I open, do stuff, close, in a loop.  I know I could do it different, but this is code that simulates use of a device by third-party software, and that software opens/closes each time.

**Comment by rfporter** [comment]
I've been running the above code for 2 days (14 million iterations). The TCP manager stops and seems to leave memory when the modbus session is closed. I don't see a memory leak. But you are certainly right about the root loop issue. This definitely warrants further investigation. I will look at how its done in the actor framework core again.

**Comment by drjdpowell** [comment]
> The TCP manager stops and seems to leave memory when the modbus session is closed. I don't see a memory leak. 

Could be some other thing stopping the clones leaving memory (or being reused) in my case.  Don't have time to investigate, I'm afraid.

**Comment by drjdpowell** [comment]
Actually, I have just checked again and it isn't happening.   But I have recently upgraded this project to LabVIEW 2020sp1 from 2017sp1, so that might be a difference.

Still, the root loop issue is a problem.

**Comment by rfporter** [comment]
How does this look?
![image](https://user-images.githubusercontent.com/6878763/194779630-b2fa8176-e07b-4e50-8a51-ed7ca0759f63.png)

Same as launch actor core. Cache the vi reference to avoid root loop synch.

Also changed core.vi to shared clone re-entrant for 0x40 option.

**Comment by drjdpowell** [comment]
Look fine, except aren't you missing an error wire into the ACBR node?

**Comment by rfporter** [comment]
Yes. Thanks for spotting that.
![image](https://user-images.githubusercontent.com/6878763/195234115-e3012d4d-9e6a-41a4-a3e6-2bef7de5bb66.png)
