### ISSUE TITLE
Not running when built into Exe in lv 2019 32

### ISSUE THREAD

**Issue by pesmith8a** [rfporter/Modbus-Master#5]
I have built a nice project using this package, that is working very well in development mode.
When I compile to exe the modbus connection will not work.  

details
LV 2019 32 bit
Windows 10 pro
using Serial interface, 38400 baud, RTU master, connecting to Automation Direct SVA 2040 Servo drive.

Paul Smith

**Comment by rfporter** [comment]
Make sure that you have the VISA runtime environment installed on the machine running the exe.
